// NOTE: this file is auto-generated by Construct
declare class IConstructProjectGlobalVariables {
	CameraZoomValue: number;
	CameraZoomTaget: number;
	ISBuildingMode: boolean;
	CollectableEffectiveRange: number;
	CollectablePlayerDmg: number;
}