// NOTE: this file is auto-generated by Construct
declare class IConstructProjectObjects {
	readonly Ground1: IObjectType<InstanceType.Ground1>;
	readonly player: IObjectType<InstanceType.player>;
	readonly Ground2: IObjectType<InstanceType.Ground2>;
	readonly wall: IObjectType<InstanceType.wall>;
	readonly wall2: IObjectType<InstanceType.wall2>;
	readonly MainCamera: IObjectType<InstanceType.MainCamera>;
	readonly Mouse: IMouseObjectType<InstanceType.Mouse>;
	readonly Browser: IObjectType<InstanceType.Browser>;
	readonly Keyboard: IKeyboardObjectType<InstanceType.Keyboard>;
	readonly BuildingModeMask: IObjectType<InstanceType.BuildingModeMask>;
	readonly TextIconExport: IObjectType<InstanceType.TextIconExport>;
	readonly Light: IObjectType<InstanceType.Light>;
	readonly EventHnadler: IObjectType<InstanceType.EventHnadler>;
	readonly Tree: IObjectType<InstanceType.Tree>;
	readonly ControlIntroductionText: IObjectType<InstanceType.ControlIntroductionText>;
	readonly BuildingModeButton: IObjectType<InstanceType.BuildingModeButton>;
	readonly BuildingModeCreatWall2: IObjectType<InstanceType.BuildingModeCreatWall2>;
	readonly BuildingModeCreatWall1: IObjectType<InstanceType.BuildingModeCreatWall1>;
	readonly BuildingModeSpButton: IObjectType<InstanceType.BuildingModeSpButton>;
	readonly YsortGroup: IFamily<InstanceType.YsortGroup>;
	readonly BuildingGroup: IFamily<InstanceType.BuildingGroup>;
	readonly ButtonGroup: IFamily<InstanceType.ButtonGroup>;
	readonly CollectableGroup: IFamily<InstanceType.CollectableGroup>;
}